### ISSUE TITLE
Loading Resources from JAR fails in experiments.sts2013baseline.util.StopwordFilter

### ISSUE THREAD

**Issue by nicolaierbs** [dkpro/dkpro-similarity#13]
Original [issue 13](https://code.google.com/p/dkpro-similarity-asl/issues/detail?id=13) created by dkpro on 2013-08-19T14:46:06.000Z:

<b>What steps will reproduce the problem?</b>

1. Download the 1.0.1 stable version of the sts2013baseline (gpl package)
2. Run Pipeline -D

Run terminates with Exception:

Caused by: java.io.FileNotFoundException: class path resource [stopwords/stopwords_english_punctuation.txt] cannot be resolved to absolute file path because it does not reside in the file system: 
jar:file:/home/someuser/.m2/repository/de/tudarmstadt/ukp/similarity/dkpro/de.tudarmstadt.ukp.similarity.dkpro.data-asl/1.0.1/de.tudarmstadt.ukp.similarity.dkpro.data-asl-1.0.1.jar!/stopwords/stopwords_english_punctuation.txt
	at org.springframework.util.ResourceUtils.getFile(ResourceUtils.java:204)
	at org.springframework.core.io.AbstractFileResolvingResource.getFile(AbstractFileResolvingResource.java:52)
	at de.tudarmstadt.ukp.similarity.experiments.sts2013baseline.util.StopwordFilter.initialize(StopwordFilter.java:75)
	... 15 more

Suggested Bugfix:

Replace res.getFile(); with res.getInputStream(); in
de.tudarmstadt.ukp.similarity.experiments.sts2013baseline.util.StopwordFilter.initialize(StopwordFilter.java:75)

**Comment by avineshpvs** [comment]
A Similar problem surfaced at sts2013baseline.util.Evaluator.java (Evaluator.java:311)

Exception in thread "main" java.io.FileNotFoundException: class path resource [goldstandards/semeval-2012/train/STS.gs.MSRpar.txt] cannot be resolved to absolute file path because it does not reside in the file system: jar:file:/home/.m2/repository/dkpro/similarity/dkpro.similarity.uima.data-asl/2.1.0/dkpro.similarity.uima.data-asl-2.1.0.jar!/goldstandards/semeval-2012/train/STS.gs.MSRpar.txt
	at org.springframework.util.ResourceUtils.getFile(ResourceUtils.java:205)
	at org.springframework.core.io.AbstractFileResolvingResource.getFile(AbstractFileResolvingResource.java:52)
	at dkpro.similarity.experiments.sts2013baseline.util.Evaluator.computePearsonCorrelation(Evaluator.java:311)
	at dkpro.similarity.experiments.sts2013baseline.util.Evaluator.runEvaluationMetric(Evaluator.java:232)
	at dkpro.similarity.experiments.sts2013baseline.Pipeline.runTrain(Pipeline.java:122)
	at dkpro.similarity.experiments.sts2013baseline.Pipeline.main(Pipeline.java:85)

**Comment by nicolaierbs** [comment]
I am not sure whether your issue has the same cause. Could you please post the line where you load the file "goldstandards/semeval-2012/train/STS.gs.MSRpar.txt"?

**Comment by avineshpvs** [comment]
I get the error at the 2nd line.
Resource res = r.getResource(gsScoresFilePath);				
File gsScoresFile = res.getFile();

**Comment by nicolaierbs** [comment]
Can you just use the file path directly? 'File file = new File("goldstandards/semeval-2012/train/STS.gs.MSRpar.txt")'? Resource is a class which provides functionality to load files from a jar in the classpath. (It should work though...)

**Comment by nicolaierbs** [comment]
The file "STS.gs.MSRpar.txt" is in the jar dkpro.similarity.uima.data-asl (version 2.1.0). Running from the command line will not work because several other dependencies are required. If you the dependencies to a maven project it should work fine.

**Comment by avineshpvs** [comment]
Thanks. I had all the dependencies in the maven project. The pipeline was running fine until this point and it was reading couple of other files from the dkpro.similarity.uima.data-asl,  just that it was not able to read this particular file.

**Comment by nicolaierbs** [comment]
Ok, I'm running out of ideas. It would be good if you could debug it. It might be due to another version of the artifact, but I'm not sure about that.

**Comment by zesch** [comment]
Could you please try to navigate to the jar in the exception
file:/home/.m2/repository/dkpro/similarity/dkpro.similarity.uima.data-asl/2.1.0/dkpro.similarity.uima.data-asl-2.1.0.jar
and then look whether the specified file is actually in there?
/goldstandards/semeval-2012/train/STS.gs.MSRpar.txt

**Comment by avineshpvs** [comment]
Yes it is there in the location.

Regards
Avinesh

**Comment by zesch** [comment]
If it is there, I don't see why the exception you have reported should be thrown.

**Comment by reckart** [comment]
'''
Exception in thread "main" java.io.FileNotFoundException: class path resource [goldstandards/semeval-2012/train/STS.gs.MSRpar.txt] cannot be resolved to absolute file path because it does not reside in the file system: jar:file:/home/.m2/repository/dkpro/similarity/dkpro.similarity.uima.data-asl/2.1.0/dkpro.similarity.uima.data-asl-2.1.0.jar!/goldstandards/semeval-2012/train/STS.gs.MSRpar.txt
at org.springframework.util.ResourceUtils.getFile(ResourceUtils.java:205)
'''

So this looks like the calling code is expecting the resource to be located in the file system and tries using getFile() to get a File object representing the resource. However, since the resource is in a JAR, it cannot be addressed using a File object.

**Comment by zesch** [comment]
Right. Thanks Richard.
I didn't saw the problem earlier as the experiment is in GPL tmp repository that still awaits its move to the main repository.

So the quick word around is to check out all of dkpro-similarity.
But in the long run we should replace the file references with streams or use ResourceUtils.resolveLocation()

**Comment by avineshpvs** [comment]
Thanks Richard and Torsten.

Regards
Avinsh
