### ISSUE TITLE
Jenkins build failing with SSL errors

### ISSUE THREAD

**Issue by logological** [dkpro/dkpro-similarity#62]
The Jenkins build on zoidberg is failing with the following errors. It doesn't seem to have anything to do with recent commits; the build fails even when reverting to the last successfully built commit.  @reckart: Is this a problem with zoidberg?

```
ERROR: Failed to retrieve remote metadata org.dkpro.similarity:dkpro-similarity:2.3.0-SNAPSHOT/maven-metadata.xml: Could not transfer metadata org.dkpro.similarity:dkpro-similarity:2.3.0-SNAPSHOT/maven-metadata.xml from/to ukp-oss (dav:https://zoidberg.ukp.informatik.tu-darmstadt.de/artifactory/public-ukp-snapshots-local): handshake alert:  unrecognized_name
org.apache.maven.artifact.deployer.ArtifactDeploymentException: Failed to retrieve remote metadata org.dkpro.similarity:dkpro-similarity:2.3.0-SNAPSHOT/maven-metadata.xml: Could not transfer metadata org.dkpro.similarity:dkpro-similarity:2.3.0-SNAPSHOT/maven-metadata.xml from/to ukp-oss (dav:https://zoidberg.ukp.informatik.tu-darmstadt.de/artifactory/public-ukp-snapshots-local): handshake alert:  unrecognized_name
	at org.apache.maven.artifact.deployer.DefaultArtifactDeployer.deploy(DefaultArtifactDeployer.java:143)
	at hudson.maven.reporters.MavenArtifactRecord.deploy(MavenArtifactRecord.java:193)
	at hudson.maven.RedeployPublisher.perform(RedeployPublisher.java:176)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
	at hudson.maven.MavenModuleSetBuild$MavenModuleSetBuildExecution.post2(MavenModuleSetBuild.java:1073)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
	at hudson.model.Run.execute(Run.java:1749)
	at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:543)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:421)
Caused by: org.eclipse.aether.deployment.DeploymentException: Failed to retrieve remote metadata org.dkpro.similarity:dkpro-similarity:2.3.0-SNAPSHOT/maven-metadata.xml: Could not transfer metadata org.dkpro.similarity:dkpro-similarity:2.3.0-SNAPSHOT/maven-metadata.xml from/to ukp-oss (dav:https://zoidberg.ukp.informatik.tu-darmstadt.de/artifactory/public-ukp-snapshots-local): handshake alert:  unrecognized_name
	at org.eclipse.aether.internal.impl.DefaultDeployer.upload(DefaultDeployer.java:447)
	at org.eclipse.aether.internal.impl.DefaultDeployer.deploy(DefaultDeployer.java:290)
	at org.eclipse.aether.internal.impl.DefaultDeployer.deploy(DefaultDeployer.java:245)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.deploy(DefaultRepositorySystem.java:420)
	at org.apache.maven.artifact.deployer.DefaultArtifactDeployer.deploy(DefaultArtifactDeployer.java:139)
	... 11 more
Caused by: org.eclipse.aether.transfer.MetadataTransferException: Could not transfer metadata org.dkpro.similarity:dkpro-similarity:2.3.0-SNAPSHOT/maven-metadata.xml from/to ukp-oss (dav:https://zoidberg.ukp.informatik.tu-darmstadt.de/artifactory/public-ukp-snapshots-local): handshake alert:  unrecognized_name
	at org.eclipse.aether.connector.basic.MetadataTransportListener.transferFailed(MetadataTransportListener.java:43)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:355)
	at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:67)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:581)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:222)
	at org.eclipse.aether.internal.impl.DefaultDeployer.upload(DefaultDeployer.java:417)
	... 15 more
Caused by: org.apache.maven.wagon.TransferFailedException: handshake alert:  unrecognized_name
	at org.apache.maven.wagon.shared.http.AbstractHttpClientWagon.fillInputData(AbstractHttpClientWagon.java:1082)
	at org.apache.maven.wagon.shared.http.AbstractHttpClientWagon.fillInputData(AbstractHttpClientWagon.java:976)
	at org.apache.maven.wagon.StreamWagon.getInputStream(StreamWagon.java:126)
	at org.apache.maven.wagon.StreamWagon.getIfNewer(StreamWagon.java:88)
	at org.apache.maven.wagon.StreamWagon.get(StreamWagon.java:61)
	at org.eclipse.aether.transport.wagon.WagonTransporter$GetTaskRunner.run(WagonTransporter.java:560)
	at org.eclipse.aether.transport.wagon.WagonTransporter.execute(WagonTransporter.java:427)
	at org.eclipse.aether.transport.wagon.WagonTransporter.get(WagonTransporter.java:404)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$GetTaskRunner.runTask(BasicRepositoryConnector.java:447)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:350)
	... 19 more
Caused by: javax.net.ssl.SSLProtocolException: handshake alert:  unrecognized_name
	at sun.security.ssl.ClientHandshaker.handshakeAlert(ClientHandshaker.java:1446)
	at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:2016)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1125)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:396)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:355)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:359)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.maven.wagon.shared.http.AbstractHttpClientWagon.execute(AbstractHttpClientWagon.java:838)
	at org.apache.maven.wagon.shared.http.AbstractHttpClientWagon.fillInputData(AbstractHttpClientWagon.java:999)
	... 28 more
```

**Comment by reckart** [comment]
Seems to have been a symptom of the recent server problems we had - one of the issues were related to DNS. I could reproduce the error via [openssl](https://stackoverflow.com/questions/7615645/ssl-handshake-alert-unrecognized-name-error-since-upgrade-to-java-1-7-0). After restarting Apache, the problem seems to be gone.
